### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lostgab** [indrekluuk/LiveOV7670#1]
cchpQUlM.ltrans0.o:(.text.startup+0x86): undefined reference to `initializeScreenAndCamera()'

cchpQUlM.ltrans0.o:(.text.startup+0x8e): undefined reference to `processFrame()'

collect2.exe: error: ld returned 1 exit status

**Comment by indrekluuk** [comment]
What exactly did you do? Did you use Arduino IDE or platformIO?

It works with my platformIO + CLion project and I tried it with Arduino IDE (downloded the zip file from github and renamed "src" folder to "LiveOV7670") and it compiled without any errors.

**Comment by lostgab** [comment]
Hey Indrek,
i am using the arduino ide, i changed the src folder to LiveOV7670 and it
says setup.h is missing
the i tried to copy the setup.h file in text form to another tab on arduino
and it did not work also,
what should i do now?
thanks
Sincerely Gabriel

**Comment by indrekluuk** [comment]
It seems that you downloaded only the .ino file. You need all the files.

Download entire project:
<img width="500" alt="screen shot 2016-12-21 at 8 34 47" src="https://cloud.githubusercontent.com/assets/1666508/21379669/740186ec-c758-11e6-8499-b23445e1cdd3.png">

After extracting the zip file you get folder "LiveOV7670-master". You need "LiveOV7670-master/arduino/src" folder. Rename the "src"->"LiveOV7670"

Additionally you need to copy "LiveOV7670-master/arduino/lib/Adafruit_GFX_Library"  to your arduino libraries folder (in you computer's home folder "Documents/Arduino/libraries") - If you have done anything with Adafruit graphics libraries before then you may already have this.

Then you should be able to open the .ino file and it should compile without errors

**Comment by lostgab** [comment]
Hey Indrek,
i did as you instructed and i still got some weird error, can i ask for
help on what to do? thanks:)
Sincerely Gabriel
[image: Inline image 1][image: Inline image 2]
[image: Inline image 3]

**Comment by indrekluuk** [comment]
What exactly the errors? I can't see any attachment images here. Could you upload the example images directly to here in github?

**Comment by lostgab** [comment]
![image](https://cloud.githubusercontent.com/assets/21375609/21449167/52302d74-c925-11e6-9fb9-2f2232e52265.png)

that is the image for my error




C:\Users\Gabri\AppData\Local\Temp\cccv5yFi.ltrans0.ltrans.o: In function `main':

cccv5yFi.ltrans0.o:(.text.startup+0x8a): undefined reference to `CameraOV7670::init()'

cccv5yFi.ltrans0.o:(.text.startup+0x94): undefined reference to `Adafruit_ST7735_mod::initR(unsigned char)'

cccv5yFi.ltrans0.o:(.text.startup+0xa0): undefined reference to `Adafruit_ST7735_mod::fillScreen(unsigned int)'

cccv5yFi.ltrans0.o:(.text.startup+0x14d8): undefined reference to `Adafruit_ST7735_mod::startAddrWindow(unsigned char, unsigned char, unsigned char, unsigned char)'

cccv5yFi.ltrans0.o:(.text.startup+0x1508): undefined reference to `Adafruit_ST7735_mod::endAddrWindow()'

C:\Users\Gabri\AppData\Local\Temp\cccv5yFi.ltrans3.ltrans.o: In function `global constructors keyed to 65535_0_ExampleTftBufferedCameraFrame.cpp.o.2004':

cccv5yFi.ltrans3.o:(.text.startup+0x3c): undefined reference to `CameraOV7670Registers::CameraOV7670Registers(unsigned char)'

cccv5yFi.ltrans3.o:(.text.startup+0x52): undefined reference to `Adafruit_ST7735_mod::Adafruit_ST7735_mod(signed char, signed char, signed char)'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

this is the error message, please help? thanks:)

**Comment by indrekluuk** [comment]
I upgraded my Arduino IDE from 1.6 to 1.8 and got a similar error.
I will fix it this weekend and report back to here when you should try again.

**Comment by indrekluuk** [comment]
It seems that Arduino IDE does not support cpp files in sub-folders anymore. Version 1.6 worked fine.
I will think of something I probably have to move them to the main folder to make it Arduino IDE compatible.

**Comment by lostgab** [comment]
Thanks bro, looking forward to the update:)

**Comment by indrekluuk** [comment]
I moved the the camera code to a library. Please try downloading the project again. But now you also have to copy LiveOV7670Library from the "lib" folder to your Arduino "libraries" folder. I tried with Arduino IDE 1.8 and it worked

**Comment by lostgab** [comment]
nope still doesnt work bro

**Comment by indrekluuk** [comment]
What is the error message? Did you copy "LiveOV7670Library" to the "libraries" folder?

**Comment by lostgab** [comment]
C:\Users\Gabri\Downloads\LiveOV7670-master\LiveOV7670-master\arduino\src\LiveOV7670\LiveOV7670.ino:10:19:
fatal error: setup.h: No such file or directory

 #include "setup.h"

                   ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

yes i did copy the library to the libraries folder
what should i do now thanks

**Comment by indrekluuk** [comment]
It seems that you opened the .ino with Arduino IDE and it automatically created sub-folder named "LiveOV7670". The problem is that all the other files are still inside in "src" folder and Arduino IDE does not see them.  
  
You have to rename the "src" folder to "LiveOV7670" (or move all the fils from "src" to the automatically created "LiveOV7670" folder)

**Comment by lostgab** [comment]
hey it solved the setup.h problem, how did u know? now there is another
problem,


C:\Users\Gabri\AppData\Local\Temp\ccHJPNuk.ltrans0.ltrans.o: In function
`setUpCamera':

C:\Users\Gabri\Documents\Arduino\libraries\LiveOV7670Library/CameraOV7670.cpp:37:
undefined reference to `CameraOV7670Registers::regsVGA'

C:\Users\Gabri\Documents\Arduino\libraries\LiveOV7670Library/CameraOV7670.cpp:37:
undefined reference to `CameraOV7670Registers::regsVGA'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by indrekluuk** [comment]
This is strange. It seems that Arduino IDE can't find cpp files in the library folder.

Does the content of the "LiveOV7670Library" look like this?
![liveov7670library](https://cloud.githubusercontent.com/assets/1666508/21592831/a7baa278-d119-11e6-9d1d-078f61181bec.png)


Did you re-download the whole project? Project folder should now look like this:

![liveov7670](https://cloud.githubusercontent.com/assets/1666508/21592899/511342e4-d11a-11e6-99fb-74cab687bc79.png)

**Comment by lostgab** [comment]
[image: Inline image 1]
[image: Inline image 2]

this is what i got

**Comment by leonhart88** [comment]
i found this error on my 1.8 TFT LCD
how to fix it?
please
![20170227_104001](https://cloud.githubusercontent.com/assets/26051049/23346997/e3858bba-fcd9-11e6-9bf0-bc2193d9e35a.jpg)

**Comment by lostgab** [comment]
the connections must be right, i cant remember exactly, here is a youtube
video to help.https://youtu.be/A9EwJ7M7OsI

**Comment by indrekluuk** [comment]
Does the example project included with the Adafruit library work?

This video:
https://www.youtube.com/watch?v=boagCpb6DgY&t=150s

**Comment by lostgab** [comment]
yes:)

**Comment by indrekluuk** [comment]
I updated to project so that at the beginning it will either flash entire screen to green if i2c connection to camera was successful or red if it failed.  
  
Could you please re-download the project and check if you see green or red screen after start-up.
Then we know if the camera setup was successful or failed.

**Comment by lostgab** [comment]
ok, ill get it done and see what happens:)ty

**Comment by syadav8126** [comment]
In file included from C:\Users\sb\Documents\Arduino\libraries\LiveOV7670Library/BufferedCameraOV7670_QQVGA_10hz.h:8:0,
                 from C:\Users\sb\AppData\Local\Temp\build8092868746636873910.tmp\ExampleTftBufferedCameraFrame.cpp:13:
C:\Users\sb\Documents\Arduino\libraries\LiveOV7670Library/BufferedCameraOV7670.h:46:17: error: 'constexpr' does not name a type
   inline static constexpr Tx getLineLength() __attribute__((always_inline));



Facing this error.....please suggest me some solution.
thank you.

**Comment by indrekluuk** [comment]
What version of Arduino IDE are you using?

"constexpr" is c++11 feature.
c++11 should be enabled for Arduino IDE for some time now.

**Comment by syadav8126** [comment]
i am using arduino ide version 1.6.5 ..
i replace" constexpr "to "cont" and resolved this problem..
the next error is "Resolution:: does not found a class or  namespace"....for that i just erase "Resolution"..and got resolved ..
now ide is asking to add some header file like ; "queue.h","twi.h","wire.h".
So does it have to be happen or I'm doing something wrong?
Thanks for your support

**Comment by syadav8126** [comment]
please suggest me proper ide and full procedure...,like the changing "src" to "Live7670".
Thanks in advance. I am looking forward to your answer..

**Comment by indrekluuk** [comment]
With the latest Arduino IDE it should compile without any errors. I think c++11 was supported from version 1.6.8, but I am not 100% sure. 1.8+ should definitely work.

If you download the latest version of the code form Github then renaming the folder is not necessary anymore. The LiveOV7670.ino is already inside folder named "LiveOV7670"

Before compiling you have to copy "LiveOV7670Library" and "Adafruit_GFX_Library" from ./src/lib/ to Arduino "libraries" folder (It should be in your home folder: ~/Documents/Arduino/libraries)
If you already have "Adafruit_GFX_Library" in your "libraries" folder then you don't have to copy that.

**Comment by syadav8126** [comment]
Thanks for your help sir... are you on whatapp so that we can solve our
query further or we have to only contact via email. Thanks again for your
support.
I am from INDIA. Thanks

**Comment by syadav8126** [comment]
After code compilation what to do next ?
java have been downloaded , the three txrx files have been moved to their specific folder. Now what to do next.

**Comment by syadav8126** [comment]
The code has been compiled successfully. How to show output of OV7670 camera on the screen using java. Please suggest something.

**Comment by indrekluuk** [comment]
Did you get both projects compiling?
1. LiveOV7670 - https://github.com/indrekluuk/LiveOV7670
2. Java project ArduinoImageCapture - https://github.com/indrekluuk/ArduinoImageCapture

**Comment by syadav8126** [comment]
The first code is Compiled  and in second, i have placed the rxtx files to
their place and installed msvc 2008. Now where to capture snap and where
can i see them?

**Comment by indrekluuk** [comment]
Does Visual Studio support java?
I personally use IntelliJ for Java. Community eddition is free.

Did you manage to compile and run the java application? A window should open where you can select com port and baudrate.

**Comment by syadav8126** [comment]
i do not know whether visual studio support java .
how to use intelliJ?
no java window is opening. It is getting complicated please tell me some solutiion.

**Comment by indrekluuk** [comment]
Install and run IntelliJ Community edition.

import project->Select folder "ArduinoImageCapture"->(Create project from existing source) Next->Next->Next->Next->Next-> (Select your Java version. For me it was "C:\Program Files\Java\jdk1.8.0_131") Next -> Finish


Now you have to add run configuration.
  
1. In the upper right corner click on the small arrow and then "Edit Configurations.."
![editconfiguration](https://cloud.githubusercontent.com/assets/1666508/25311654/91ed3670-280f-11e7-98ca-6beaa1be4261.png)  

2. Click on the "+" and select "Application"
![addnew](https://cloud.githubusercontent.com/assets/1666508/25311665/d6772e7c-280f-11e7-99e0-222a3fbe2fcc.png)

3. Name the configuration and select main java class
![selecttarget](https://cloud.githubusercontent.com/assets/1666508/25311682/20783886-2810-11e7-8ae7-6ecf5cee3a85.png)

4. Now if you have copied these files to correct location in JAVA folder
Copy RXTXcomm.jar ---> <JAVA_HOME>/jre/lib/ext
Copy librxtxSerial.so ---> <JAVA_HOME>/jre/lib/i386/
Copy librxtxParallel.so ---> <JAVA_HOME>/jre/lib/i386/
You should be able to run the application by clicking the green arrow in the upper right corner.
![run](https://cloud.githubusercontent.com/assets/1666508/25311701/6b3b2c0c-2810-11e7-8d70-1218eb92da40.png)

And application window should open
![mainwindow](https://cloud.githubusercontent.com/assets/1666508/25311714/983cd91c-2810-11e7-9827-48360fd00de5.png)

**Comment by leonhart88** [comment]
how is it works on arduino mega 2560?
i've already compile using Arduino Uno it's working but in Arduino/Genuino Mega or Mega 2560 board and Processor ATmega 2560(mega2560). But the message shows :

In file included from C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/BufferedCameraOV7670.h:8:0,

                 from C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/BufferedCameraOV7670_QQVGA_10hz.h:8,

                 from C:\Users\Anthony\AppData\Local\Temp\buildd92f8e36536f19f59eabeec9e696f075.tmp\sketch\ExampleTftBufferedCameraFrame.cpp:13:

C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/CameraOV7670.h: In member function 'void CameraOV7670::waitForVsync()':

C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/CameraOV7670.h:133:10: error: 'OV7670_VSYNC' was not declared in this scope

   while(!OV7670_VSYNC);

          ^

C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/CameraOV7670.h: In member function 'void CameraOV7670::waitForPixelClockLow()':

C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/CameraOV7670.h:142:9: error: 'OV7670_PIXEL_CLOCK' was not declared in this scope

   while(OV7670_PIXEL_CLOCK);

         ^

C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/CameraOV7670.h: In member function 'void CameraOV7670::waitForPixelClockHigh()':

C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/CameraOV7670.h:146:10: error: 'OV7670_PIXEL_CLOCK' was not declared in this scope

   while(!OV7670_PIXEL_CLOCK);

          ^

C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/CameraOV7670.h: In member function 'uint8_t CameraOV7670::readPixelByte()':

C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library/CameraOV7670.h:150:10: error: 'OV7670_PIXEL_BYTE' was not declared in this scope

   return OV7670_PIXEL_BYTE;

          ^

Using library Adafruit_GFX_Library at version 1.1.5 in folder: C:\Program Files (x86)\Arduino\libraries\Adafruit_GFX_Library 
Using library SPI at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI 
Using library LiveOV7670Library in folder: C:\Program Files (x86)\Arduino\libraries\LiveOV7670Library (legacy)
Using library Wire at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire 
exit status 1
Error compiling.

Help me Please...

**Comment by indrekluuk** [comment]
I have modified the library so it will now compile for Arduino Mega (you have to re-download "LiveOV7670Library").

But I don't know if it actually works with Mega. I have not tested it.

**Comment by leonhart88** [comment]
it's not working yet, but can be compiled
I've change the pin before for TFT LCD, because it's not working (TFT only). So, i change it to
SPI clock/SCL 	- PIN 13 (5V -> 3.3V)  --> change to 52
SPI data/SDA 	- PIN 11 (5V -> 3.3V) --> change to 51
should i change the connection pin on OV7670?
